### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by robneu** [FlagshipWP/flagship-wp-theme-config#1]
A few tasks are running much slower than they should be. I think it's because of how the paths are defined for them. The slowest tasks are `addtextdomain`, `checktextdomain`, and `replace`.

**Comment by ctalkington** [comment]
might be good to re-evaluate if recent changes to excluding composer and such have helped this at all.

**Comment by robneu** [comment]
I actually meant to make a note about this. It looks like it has helped considerably. What use to take ~50 seconds on my local now takes ~20-23 seconds.

**Comment by ctalkington** [comment]
ah nice i think between the changes to wp-i18n to excluding files in folders that match the exclude and excluding composer in flagship config it prob cut down the files scanned by over half

**Comment by robneu** [comment]
I think performance is about as good as it's going to get for now. Closing this out.
