### ISSUE TITLE
Reduce Complexity

### ISSUE THREAD

**Issue by robneu** [FlagshipWP/flagship-wp-theme-config#7]
There are a number of things in this config that I don't really find useful at all. In particular all of the linting functions, log creation, etc.

I'm a big fan of linting, but I don't need it to run on build. It's integrated into my development workflow in my editor. I realize not everyone does this, but I also don't really care. If they don't want to lint files it's not really my job to force them to do so.

Is anyone actively using any of these? If not, I'm considering pulling them out just to have fewer dependencies.

**Comment by ctalkington** [comment]
i personally have never called the `check` alias and have only ever left lint in watch config for gruntfile changes.

**Comment by robneu** [comment]
These are the depdencies I'm considering removing:

```
custom log task
grunt-bump
grunt-checktextdomain
grunt-complexity
grunt-contrib-jshint
grunt-githooks
grunt-jscs
grunt-jsonlint
grunt-jsvalidate
grunt-scss-lint
semver
```

I have literally never used any of them other than when they're called automatically by watch, build, etc. We don't really have a formal release task of any kind, so `grunt-bump` and `semver` etc seem kind of useless.

It might be useful to actually implement a more formal release task, but I've never actually tried to automate it before so I'm not sure how to build it...

**Comment by ctalkington** [comment]
i definitely feel that release type tasks (githooks,bump,semver) are something that everyone is going to do different and since theres not a defined workflow at this point, its most likely being used differently by every person/shop.

i think the checktextdomain could stay but i think latest versions of wp-i18n make it a bit defunct since you can now replace all textdomains in one swoop.

**Comment by robneu** [comment]
That makes sense. Yeah, for our purposes just being able to zip up a versioned copy is plenty, but I know a lot of people like to actually automate deployment and everything. I've never really found deployment to be enough of a burden to warrant automation, but it seems like I may be in the minority there.

I thought the same about `grunt-checktextdomin`. It was handy before, but now that they're all replaced in a single pass it seems a little pointless. I guess it is still useful to make sure there weren't any issues when the replacement was run...

**Comment by ctalkington** [comment]
also at the end of the day, the way grunt config is loaded, it takes maybe 2 min to add these back in your own base.

**Comment by robneu** [comment]
Exactly. I think I'll go ahead and get rid of these, but I'll keep `grunt-checktextdomain` for now. Even if it's rarely used I think it's still useful enough to keep.
